---
title: "Dplyr Advanced"
output: html_notebook
---


```{r}
library(dplyr)
library(readr)
billboard100 <- read_csv("billboard100.csv")
```
```{r}
billboard100 %>% select(date:artist, weeks_popular='weeks-on-board')
```

```{r}
library(lubridate) #Facilita la manipulación y el formateo de fechas
library(stringr) #Proporciona funciones para la manipulación y el análisis de cadenas de texto
```


```{r}
music_df.cleaned <- billboard100 %>%
  mutate(date = ymd(date),
         primary_artist = ifelse(str_detect(artist, 'Featuring'),
                          str_match(artist,'(.*)\\sFeaturing')[,2],
                          artist),
         featured_artist = str_match(artist,'Featuring\\s(.*)')[,2]) %>%
  select(date,song,primary_artist,featured_artist)
music_df.cleaned
```

```{r}
library(tidyr) #Ofrece herramientas para realizar manipulaciones y transformaciones de datos, especialmente en relación con la reorganización de datos en formato "tidy".
```

```{r}
music_df.cleaned %>% 
  distinct(song, primary_artist, featured_artist) %>%
  pivot_longer(2:3,
              names_to="artist_type",
              values_to="artist_name")%>%
  filter(artist_name=="Taylor Swift") %>%
  count(artist_type)
```

```{r}
billboard100 %>%
  filter(rank <= 3) %>%
  select(date, rank, song) %>%
  pivot_wider(names_from="rank",values_from="song")
```


```{r}
mtv_data = read_csv("10000-MTV-Music-Artists-page-1.csv")
```

```{r}
top5_genres <- music_df.cleaned %>%
  inner_join(mtv_data, by = c("primary_artist" = "name")) %>%
  select(song, primary_artist, genre) %>%
  filter(!is.na(genre)) %>%
  distinct() %>%
  count(genre) %>%
  top_n(5) %>%
  arrange(desc(n)) %>%
  pull(genre)
top5_genres
```

```{r}
library(ggplot2)
```

```{r}
music_df.cleaned %>%
  inner_join(mtv_data, 
             by = c("primary_artist" = "name")) %>%
  select(date,song,genre) %>%
  mutate(date=floor_date(date, unit="year")) %>%
  filter(genre %in% top5_genres) %>%
  count(date, genre) %>%
  ggplot(aes(x=date,y=n,color=genre)) + geom_line()
```





