---
title: "PEAJES"
output: html_document
date: "2023-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Historico Peajes Colombia Trafico y Recaudo

Fuente: <https://www.kaggle.com/datasets/martinaltamar/historico-peajes-colombia-trafico-y-recaudo>.

Tamaño:
Filas: 98306
Columnas: 11

```{r}
library(dplyr)
library(ggplot2)
library(dslabs)
library(readr)
peajes <- read.csv('peajes_colombia.csv')

```
# categoria vs tarifa histo
# categoria vs evasores pie
# categoria vs flujo (barras)

```{r}
Fecha = as.Date(peajes$FechaDesde,'%d/%m/%Y')
año <- as.numeric(format(Fecha,'%Y'))
df=peajes
data <-filter(df, IdCategoriaTarifa %in% c("I","II","III"))
#select(peajes$Peaje,BPSysAve) %>%
```

```{r}

ggplot(data, aes(x = ValorTarifa))+
  geom_histogram()+
  facet_wrap(~ IdCategoriaTarifa, nrow=3)

```


```{r}

#agrupar los datos. y luego si hacerlo ? 
data%>%
  
  select(IdCategoriaTarifa,TraficoEvasores)%>%
  filter(TraficoEvasores!="NULL) %>%
  group_by(IdCategoriaTarifa)%>%
  
  summarise(mean(IdCategoriaTarifa, na.rm = TRUE))

#ggplot(data, aes(x=IdCategoriaTarifa,y=data$Trafico))+
#  geom_point()
  

```

















```{r}
#peajes$Peaje

peajes %>% ggplot(aes(x = peajes$Peaje, 
                       y = peajes$Trafico)) + 
  geom_point()+xlab("Populations in millions (log scale)") + 
  ylab("Total number of murders (log scale)") +
  ggtitle("US Gun Murders in 2010")

```

#categorias vs flujo
#categorias vs evasores
