---
title: "Leer_Datasets"
author: "NSM"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(dslabs)

data("heights")
head(heights)
```
```{r}
s<- heights %>%
  filter(sex == "Female") %>%
  summarise(promedio = mean(height), desviación_estandar = sd(height))
s

```

```{r}
data(murders)
murders<-murders %>% mutate(rate = total/population*100000)
head(murders)
```

```{r}
#calcula la media de la tasa de asesinatos
summarise(murders,mean(rate))
meanrateEEUU <-murders %>% mutate(rate = total/population*100000)%>% summarise(mean(rate)); meanrateEEUU
```

```{r}
#multiple summaries
a<-heights %>%
  filter(sex == "Female") %>%
  summarise(median_min_max = quantile(height, c(0.5, 0, 1)))

median_min_max <- function(x) {
  qs <- quantile(x, c(0.5,0,1))
  data.frame(median = qs [1], minimum = qs[2], maximum =qs[3])
}
```


















